hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Konzipiere und programmiere dein eigenes Rollenspiel (RPG) Labyrinth-Spiel.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: 'Einführung'
- title: Neue Zimmer hinzufügen
- title: 'Aufgabe: Neue Zimmer hinzufügen'
- title: Gegenstände zum Einsammeln hinzufügen
- title: 'Aufgabe: Neue Gegenstände hinzufügen'
- title: Feinde (Monster) hinzufügen
- title: 'Aufgabe: Noch mehr Monster hinzufügen'
- title: Das Spiel gewinnen
- title: 'Aufgabe: Entwickele dein eigenes Spiel'